### ISSUE TITLE
Would love to see a screenshot....

### ISSUE THREAD

**Issue by PySimpleGUI** [LesNewell/solar-calculator#1]
Do you have a screenshot you could drop into your readme so we can all see what ya made?  I'm sure visitors would enjoy seeing your GUI (or maybe it's just me, but I think others would like to see it too)

**Comment by LesNewell** [comment]
The GUI is pretty basic but I have added a couple of screen shots.
One issue I have with PySimpleGUI is that I can't easily remove controls. In the 'rules' window I need to add/remove rows to the tables. Currently I close the window and redraw it but that's pretty ugly.
